baseURL = "https://www.brookshelley.com/"
languageCode = "en-us"
title = "dill & fennel"
theme = "ezhil"

copyright = "Â© Copyright Brook Shelley 2020"


# Enable syntax highlighting.
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 5

[params]
	mainSections = ["posts"]
  subtitle = "a blog"
	disableDisqusTypes = ["page", "posts"]
	disableDateTypes = ["page"]
  featherIconsCDN = true
	# excludedTypes = ["mediadiet"]
	favicon = "/favicon.ico"
	logo = "/666.png"
	mode = "dark" # "dark", "auto", "light"
        # customCSS = "css/custom.css"  # Custom CSS applied to default styles.
        # customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
        # customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]

  [[menu.main]]
    name = "archive"
    url = "/posts"
    weight = 5

  [[menu.main]]
    name = "media diet"
    url = "/mediadiet"
    weight = 4

  [[menu.footer]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "reading"
    url = "/books"
    weight = 1

  [[menu.main]]
    name = "watching"
    url = "/movies"
    weight = 2

  [[menu.main]]
    name = "writing"
    url = "/writing"
    weight = 3

[[menu.main]]
    name = "newsletter"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "https://buttondown.email/brookshelley"
    weight = 6

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/brookshelley"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/brookshelley"
